FROM golang:1.20-bullseye

RUN apt-get update && apt-get install -y git bash gcc libc6-dev gettext

WORKDIR /app

# Get source for Dex
RUN git clone https://github.com/dexidp/dex.git .
RUN git checkout v2.37.0

# Build Dex
RUN go build -o dex ./cmd/dex

# Run Dex
RUN cp dex /usr/bin/dex