issuer: http://localhost:5556
authorization_endpoint: http://dex:5556/auth
token_endpoint: http://dex:5556/token
jwks_uri: http://localhost:5556/keys
userinfo_endpoint: http://localhost:5556/userinfo
device_authorization_endpoint: http://localhost:5556/device/code

# Storage configuration to use MongoDB
storage:
  type: memory

web:
  http: 0.0.0.0:5556

staticClients:
  - id: ${OIDC_CLIENT_ID}
    redirectURIs:
      - http://localhost:8000/authorize
    name: ${OIDC_CLIENT_NAME}
    secret: ${OIDC_CLIENT_SECRET}

enablePasswordDB: true

# How to create passwords
# python -c "import bcrypt; print(bcrypt.hashpw(b'password', bcrypt.gensalt()).decode())"
staticPasswords:
  - email: admin@mail.com
    hash: "$2b$10$8NoCpIs/Z6v0s/pU9YxYIO10uWyhIVOS2kmNac9AD0HsqRhP5dUie" # password = "password"
    username: admin
    userID: "123"

  - email: mod@mail.com
    hash: "$2b$10$8NoCpIs/Z6v0s/pU9YxYIO10uWyhIVOS2kmNac9AD0HsqRhP5dUie" # password = "password"
    username: moderator
    userID: "124"

  - email: sam@mail.com
    hash: "$2b$10$8NoCpIs/Z6v0s/pU9YxYIO10uWyhIVOS2kmNac9AD0HsqRhP5dUie" # password = "password"
    username: sam
    userID: "131"

  - email: paris@mail.com
    hash: "$2b$10$8NoCpIs/Z6v0s/pU9YxYIO10uWyhIVOS2kmNac9AD0HsqRhP5dUie" # password = "password"
    username: paris
    userID: "132"

  - email: shannon@mail.com
    hash: "$2b$10$8NoCpIs/Z6v0s/pU9YxYIO10uWyhIVOS2kmNac9AD0HsqRhP5dUie" # password = "password"
    username: shannon
    userID: "133"

oauth2:
  skipApprovalScreen: true